
modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="projecttest"
version="1.0.0"
displayName="ProjectTest"
displayURL=""
credits="PyModder, MFF anf Forge guys"
authors="LavaPower"
description="Ceci est un mod de test avec PyModder."

[[dependencies.projecttest]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.projecttest]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"
