BLOCK_MATERIALS = [
    "AIR", "STRUCTURE_VOID", "PORTAL", "CARPET", "PLANTS", "OCEAN_PLANT", "TALL_PLANTS", "SEA_GRASS", "WATER",
    "BUBBLE_COLUMN", "LAVA", "SNOW", "FIRE", "MISCELLANEOUS", "WEB", "REDSTONE_LIGHT", "CLAY", "EARTH", "ORGANIC",
    "PACKED_ICE", "SAND", "SPONGE", "SHULKER", "WOOD", "BAMBOO_SAPLING", "BAMBOO", "WOOL", "TNT", "LEAVES", "GLASS",
    "ICE", "CACTUS", "ROCK", "IRON", "SNOW_BLOCK", "ANVIL", "BARRIER", "PISTON", "CORAL", "GOURD", "DRAGON_EGG",
    "CAKE"
]

ITEMGROUP = [
    "BUILDING_BLOCKS", "DECORATIONS", "REDSTONE", "TRANSPORTATION", "MISC", "SEARCH", "FOOD", "TOOLS", "COMBAT",
    "BREWING", "MATERIALS"
]

ELEMENTS = [
    "SimpleBlock", "ItemGroup"
]

ICON_BLOCKS = [
    "STONE", "GRANITE", "DIORITE", "ANDESITE", "GRASS_BLOCK", "DIRT", "COBBLESTONE", "OAK_PLANKS", "BEDROCK", "SAND",
    "GRAVEL", "OAK_LOG", "OAK_WOOD", "STRIPPED_OAK_WOOD", "OAK_LEAVES", "SPONGE", "GLASS", "LAPIS_BLOCK",
    "DISPENSER", "SANDSTONE", "NOTE_BLOCK", "STICKY_PISTON", "COBWEB", "PISTON", "WHITE_WOOL", "GOLD_BLOCK",
    "IRON_BLOCK", "BRICKS", "TNT", "BOOKSHELF", "OBSIDIAN", "SPAWNER", "OAK_STAIRS", "CHEST", "DIAMOND_ORE",
    "DIAMOND_BLOCK", "CRAFTING_TABLE", "FURNACE", "OAK_SIGN", "OAK_DOOR", "RAIL", "COBBLESTONE_STAIRS",
    "STONE_PRESSURE_PLATE", "IRON_DOOR", "REDSTONE_TORCH", "STONE_BUTTON", "SNOW_BLOCK", "CACTUS", "CLAY", "SUGAR_CANE"
]